### ISSUE TITLE
Could not clone princess

### ISSUE THREAD

**Issue by vahidAK** [MeHelmy/princess#1]
Hi @MeHelmy ,

I face this error when I want to clone princess:

> (base) [vakbari@gphost07 princess]$ git clone git@github.com:MeHelmy/princess.git
> Cloning into 'princess'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights and the repository exists.

How can I clone it?
Many thanks,
Vahid.

**Comment by vahidAK** [comment]
It was solved by cloning from github itself
thanks

**Comment by MeHelmy** [comment]
Thanks, I will close it.
