### ISSUE TITLE
ModuleNotFoundError: No module named 'skbuild'

### ISSUE THREAD

**Issue by SaintBacchus** [MeHelmy/princess#2]
Hello @MeHelmy 
When I try to install princess, the last step will throw this error message.

Can you tell me your hardware and software environment of this software? 
Or you can make a Docker image of this software and publish it to DockerHub, then anyone can use your software easy.
```bash
    Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/w
heel-0.33.6-py2.py3-none-any.whl
  Collecting scikit-build
    Using cached https://files.pythonhosted.org/packages/8a/b5/c6ca60421991c22e69b9a950b0d046e06d714f79f7071946ab885c7115fb/s
cikit_build-0.10.0-py2.py3-none-any.whl
  Collecting cmake
    Using cached https://files.pythonhosted.org/packages/0a/f5/3212616a15b4112d7ad075a407f007eac2cac59292a9d973f2ee7e3c4068/c
make-3.13.2.post1.tar.gz
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-jnys9rno/cmake/setup.py", line 7, in <module>
          from skbuild import setup
      ModuleNotFoundError: No module named 'skbuild'
  
      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jnys9rno/cmake/
  You are using pip version 18.1, however version 20.0.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by MeHelmy** [comment]
First I'm assuming that the current python installation you have is `Python 3.7`.
You can check which python version you have by running `python --version `
If the python version you have is not `3.7` you can use conda installation to do that `conda install python=3.7`
Princess is currently developed on `CentOS release 6.7`

For your error try this first `pip install --upgrade setuptools`  then:
In your installation directory go to bin `cd bin`
~~~
wget https://github.com/squeaky-pl/portable-pypy/releases/download/pypy3.6-7.2.0/pypy3.6-7.2.0-linux_x86_64-portable.tar.bz2
mv pypy* pypy.tar.bz2
tar -xvjf pypy.tar.bz2
cd ..
export PATH="$PWD"/bin/pypy/bin:$PATH
wget https://bootstrap.pypa.io/get-pip.py
pypy3 -m ensurepip
pypy3 -m pip install --no-cache-dir intervaltree blosc
~~~

Currently, we are working on Docker, but I do not think it will be available soon, so for know try what I suggested earlier and let see if that will solve the issue.

~Best,
Medhat
