### ISSUE TITLE
ModuleNotFoundError: No module named 'skbuild'

### ISSUE THREAD

**Issue by ainovice1992** [MeHelmy/princess#4]
Hello @MeHelmy
When I try to install princess, the last step will throw this error message，ModuleNotFoundError: No module named 'skbuild'.
I have tried this method，refer to https://github.com/MeHelmy/princess/issues/2，but I failed too.

Configuration：
    Ubuntu 5.4.0-6ubuntu1~16.04.5
    python3.7.3

Can I change "pypy3 -m ensurepip pypy3 -m pip install --no-cache-dir intervaltree blosc" to "python -m ensurepip pyhton -m pip install --no-cache-dir intervaltree blosc" in install.sh。

best，
XFY

**Comment by MeHelmy** [comment]
Can you please put the full error message.
Thanks,
Medhat

**Comment by NGLJ** [comment]
Collecting scikit-build
    Downloading http://cmc-cd-mirror.rnd.huawei.com/pypi/packages/8a/b5/c6ca60421991c22e69b9a950b0d046e06d714f79f7071946ab885c7115fb/scikit_build-0.10.0-py2.py3-none-any.whl (66kB)
  Collecting cmake
    Downloading http://cmc-cd-mirror.rnd.huawei.com/pypi/packages/a5/7c/6525cadf99abbabbcb29676f53de0441e8d2f8d0114ab52aae2b31223a3b/cmake-3.16.3.tar.gz
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-_563pm8h/cmake/setup.py", line 7, in <module>
          from skbuild import setup
      ModuleNotFoundError: No module named 'skbuild'

      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_563pm8h/cmake/
  You are using pip version 18.1, however version 20.0.2 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.

  ----------------------------------------
Command "/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/bin/pypy3.6-7.2.0-linux_x86_64-portable/bin/pypy3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-6pgtrvt5 --no-warn-script-location --no-binary :none: --only-binary :none: -i http://cmc-cd-mirror.rnd.huawei.com/pypi/simple/ --trusted-host cmc-cd-mirror.rnd.huawei.com -- setuptools wheel scikit-build cmake ninja" failed with error code 1 in None
You are using pip version 18.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Done

**Comment by ainovice1992** [comment]
Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/w
heel-0.33.6-py2.py3-none-any.whl
  Collecting scikit-build
    Using cached https://files.pythonhosted.org/packages/8a/b5/c6ca60421991c22e69b9a950b0d046e06d714f79f7071946ab885c7115fb/s
cikit_build-0.10.0-py2.py3-none-any.whl
  Collecting cmake
    Using cached https://files.pythonhosted.org/packages/0a/f5/3212616a15b4112d7ad075a407f007eac2cac59292a9d973f2ee7e3c4068/c
make-3.13.2.post1.tar.gz
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-jnys9rno/cmake/setup.py", line 7, in <module>
          from skbuild import setup
      ModuleNotFoundError: No module named 'skbuild'
  
      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jnys9rno/cmake/
  You are using pip version 18.1, however version 20.0.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by MeHelmy** [comment]
I just made some changes to the installation file, can you please update `git pull` or just download `install.sh` file and run the installation again, please keep me updated. 


Thanks,
Medhat

**Comment by ainovice1992** [comment]
HI,
I install princess on a local machine successful at your suggestion，but a new problem happended when I run princess. 

My command:
./princess -c all -s /mnt/data1/lixinyue/docker/nextdenovo/NextDenovo/r94_ec_rad2.181119.60x-10kb.fasta -d ./result -r ont -e

Building DAG of jobs...
InputFunctionException in line 101 of /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/result/modules/snp.smk:
KeyError: '22'
Wildcards:
aligner=minimap
chr=22
Traceback (most recent call last):
  File "./princess", line 190, in <module>
    main()
  File "./princess", line 185, in main
    args = get_args()
  File "./princess", line 53, in get_args
    args.func(args, unknownargs)
  File "./princess", line 138, in run_princess
    subprocess.run(['snakemake',  '-p', '-j', number_of_jobs, '--cluster-config', cluster_config, '--config', sample_dir, sample_names, *unknownargs], check=True, universal_newlines=True)
  File "/root/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['snakemake', '-p', '-j', '200', '--cluster-config', '/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/result/cluster_config.yaml', '--config', 'sample_directory=/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/result', 'sample_list=r94_ec_rad2.181119.60x-10kb.fasta', 'read_type=ont', '--use-conda']' returned non-zero exit status 1.

**Comment by MeHelmy** [comment]
Can you please show me the `Information about reference` section from `config.yaml` and `head the genome.fa.fai` that you are using.  I am thinking that the reference you have it contains `chr22` not `22` .

**Comment by ainovice1992** [comment]
config.yaml:
### Information about reference
###########################
ref: ['37']
references:
  '37': "/mnt/data1/lixinyue/data/hg19.fa"
  '38': ""
chr_list:
  '37': ['22'] #['1','2','3']
  '38': [] #[chr1,chr2]
###########################

**Comment by MeHelmy** [comment]
Can you please `head /mnt/data1/lixinyue/data/hg19.fa.fai`. So we can identify chromosome named  `22` or `chr22`.

**Comment by ainovice1992** [comment]
hg.fa.fai:
chr1	249250621	6	50	51
chr2	243199373	254235646	50	51
chr3	198022430	502299013	50	51
chr4	191154276	704281898	50	51
chr5	180915260	899259266	50	51
chr6	171115067	1083792838	50	51
chr7	159138663	1258330213	50	51
chr8	146364022	1420651656	50	51
chr9	141213431	1569942965	50	51
chr10	135534747	1713980672	50	51
chr11	135006516	1852226121	50	51
chr12	133851895	1989932775	50	51
chr13	115169878	2126461715	50	51
chr14	107349540	2243934998	50	51
chr15	102531392	2353431536	50	51
chr16	90354753	2458013563	50	51
chr17	81195210	2550175419	50	51
chr18	78077248	2632994541	50	51
chr19	59128983	2712633341	50	51
chr20	63025520	2772944911	50	51
chr21	48129895	2837230949	50	51
chr22	51304566	2886323449	50	51
chrX	155270560	2938654113	50	51
chrY	59373566	3097030091	50	51
chrM	16571	3157591135	50	51

**Comment by MeHelmy** [comment]
Thanks,

As we can see the chromosome name is `chr22` so it should be `'37': ['chr22']` instead of `'37': ['22']`.

~Best,
Medhat

**Comment by ainovice1992** [comment]
Do you mean change to 
###########################
ref: ['38']
references:
  '37': ""
  '38': "/mnt/data1/lixinyue/data/hg19.fa"
chr_list:
  '37': [''] #['1','2','3']
  '38': ["chr22"] #[chr1,chr2]
###########################

**Comment by MeHelmy** [comment]
We are using reference hg19 right?

So it should be
```
###########################
ref: ['37']
references:
     '37': "/mnt/data1/lixinyue/data/hg19.fa"
     '38': ""
chr_list:
     '37': ['chr22'] #['1','2','3']
     '38': ["] #[chr1,chr2]
###########################
```

**Comment by ainovice1992** [comment]
Thanks,
When I run
“./princess -c all -s /mnt/data1/lixinyue/docker/nextdenovo/NextDenovo/r94_ec_rad2.181119.60x-10kb.fasta -d ./analysis_37 -r ont -e”
to "5 of 29 steps (17%) done",  An error occurred，as follows:

Activating conda environment: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/.snakemake/conda/cbd00219
Activating conda environment: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/.snakemake/conda/42435982
Activating conda environment: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/.snakemake/conda/cbd00219
Delay 4 seconds before starting variant calling ...
Delay 9 seconds before starting variant calling ...
[Thu Feb 13 12:00:41 2020]
Error in rule sniffles:
    jobid: 11
    output: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/sv/minimap/sniffles.vcf
    log: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/sv/minimap/sniffles.log (check log file(s) for error message)
    conda-env: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/.snakemake/conda/42435982
    shell:

        sniffles --min_support 2 --mapped_reads /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/align/minimap/data.bam --vcf /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/sv/minimap/sniffles.vcf --num_reads_report -1 --genotype --report_seq  > /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/sv/minimap/sniffles.log 2>&1

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job sniffles since they might be corrupted:
/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/sv/minimap/sniffles.vcf
[Thu Feb 13 12:00:42 2020]
Finished job 27.

best,
XFY

**Comment by ainovice1992** [comment]
Another error:
9 of 29 steps (31%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
mkdir -p /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/snake_l                        og &&    find . -maxdepth 1 -name 'snakejob.*' -type f -print0 | xargs -0r mv -t /mnt/dat                        a1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/snake_log &&    cat pict                        ures/fail.txt

Please contact helmy dot medhat [@] gmail for more information
Complete log: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/.s                        nakemake/log/2020-02-13T130001.399725.snakemake.log
Traceback (most recent call last):
  File "./princess", line 191, in <module>
    main()
  File "./princess", line 186, in main
    args = get_args()
  File "./princess", line 53, in get_args
    args.func(args, unknownargs)
  File "./princess", line 139, in run_princess
    subprocess.run(['snakemake',  '-p', '-j', number_of_jobs, '--cluster-config', cluster                        _config, '--config', sample_dir, sample_names, *unknownargs], check=True, universal_newli                        nes=True)
  File "/root/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['snakemake', '-p', '-j', '200', '--cluster-confi                        g', '/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/cluster_con                        fig.yaml', '--config', 'sample_directory=/mnt/data1/lixinyue/docker/test_xfy/princess/pri                        ncess-master/analysis_37', 'sample_list=r94_ec_rad2.181119.60x-10kb.fasta', 'read_type=on                        t', '--use-conda']' returned non-zero exit status 1.

best,
XFY

**Comment by MeHelmy** [comment]
Both errors are for the same thing, can we see the error? please, `cat /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/sv/minimap/sniffles.log` and put its content here.

Thanks,
Medhat

**Comment by ainovice1992** [comment]
/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/sv/minimap/sniffles.log：
Estimating parameter...
Too few reads detected in /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/align/minimap/data.bam
best,
XFY

**Comment by MeHelmy** [comment]
Exactly as the error mentioning **`Too few reads detected`**, maybe you should use a  file with more reads (e.x all reads in chr22) otherwise neither SVs nor SNVs will be identified and will result in errors.

**Comment by ainovice1992** [comment]
Hi,
Excuse, I don't understand what you mean.

**Comment by ainovice1992** [comment]
When I run use:
./princess -c all -s /mnt/data1/lixinyue/docker/nextdenovo/NextDenovo/r94_ec_rad2.181119.60x-10kb.fasta -d ./analysis_37 -r ont -e -npr

Results like:
Job counts:
        count   jobs
        1       SV_SNP_compained
        1       add_rg
        1       all
        1       all_phased
        1       bam_2_tab
        1       bam_stat
        2       bgzip_file
        2       call_snps_chunk
        1       change_sample_name
        1       concat_chromosome
        1       gt
        3       index_bam
        1       merge_align
        1       minimap2
        1       partion_bam
        1       phase_sv
        1       phasing
        1       reads_stat
        1       sniffles
        1       snp_stat
        1       stat
        1       sv_stat
        2       vcf_index
        1       vcf_sort
        29
This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.

**Comment by MeHelmy** [comment]
Yes because it is a dry run to see what will run on your data as we mentioned here https://github.com/MeHelmy/princess/issues/3#issuecomment-584863553 
Now for the actuall run use:

`./princess -c all -s /mnt/data1/lixinyue/docker/nextdenovo/NextDenovo/r94_ec_rad2.181119.60x-10kb.fasta -d ./analysis_37 -r ont -e`

>  Excuse, I don't understand what you mean.

You are using a small data set, as a result, Sniffles will not be able to identify  SVs. The solution is to use more data.

**Comment by NGLJ** [comment]
Is because of "sample_extension" is set to "gz"?

# Information about samples
###########################
sample_directory: "" # samples by default should exist in this directory unless otherwise.
read_type: "ont" # ont,clr or ccs
sample_extension: "fasta" # please add sample extension ex: fastq , fasta or gz # defaul gz
# sample list If specified this will overlap the default behavior which is all samples in directory specified above.
# If you leave empty the input will be all the samples in directory.
sample_list: []
###########################

best,
XFY

**Comment by ainovice1992** [comment]
Is because of "sample_extension" is set to "gz"?

#### Information about samples
###########################
sample_directory: "" # samples by default should exist in this directory unless otherwise.
read_type: "ont" # ont,clr or ccs
sample_extension: "gz" # please add sample extension ex: fastq , fasta or gz # defaul gz
##### sample list If specified this will overlap the default behavior which is all samples in directory specified above.
##### If you leave empty the input will be all the samples in directory.
sample_list: []
###########################

**Comment by MeHelmy** [comment]
No, it is because you are using too few reads number in your file `/mnt/data1/lixinyue/docker/nextdenovo/NextDenovo/r94_ec_rad2.181119.60x-10kb.fasta`

**Comment by ainovice1992** [comment]
Could you share me your fasta data. Download url?
best,
XFY

**Comment by NGLJ** [comment]
Which version does bgzip require？
best,
XFY

**Comment by ainovice1992** [comment]
Run to "23 of 31 steps", Another error occurred.

23 of 31 steps (74%) done
[Fri Feb 14 14:15:07 2020]
Job 24: Extracting read hp and ps info from tagged bam file.
        samtools view  /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/align/minimap/data_hap.bam |  grep  "PS:i:" |  awk 'BEGIN{OFS="\t";}{print $1,$(NF-2), $(NF)}'  > /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/align/minimap/data_hap.tab

Activating conda environment: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/.snakemake/conda/42435982
[Fri Feb 14 14:15:25 2020]
Error in rule bam_2_tab:
    jobid: 24
    output: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/align/minimap/data_hap.tab
    conda-env: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/.snakemake/conda/42435982
    shell:
        samtools view  /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/align/minimap/data_hap.bam |  grep  "PS:i:" |  awk 'BEGIN{OFS="\t";}{print $1,$(NF-2), $(NF)}'  > /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/align/minimap/data_hap.tab
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Removing output files of failed job bam_2_tab since they might be corrupted:
/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/align/minimap/data_hap.tab
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
mkdir -p /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/snake_log &&    find . -maxdepth 1 -name 'snakejob.*' -type f -print0 | xargs -0r mv -t /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/snake_log &&    cat pictures/fail.txt
Please contact helmy dot medhat [@] gmail for more information
Complete log: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/.snakemake/log/2020-02-14T140809.823470.snakemake.log
Traceback (most recent call last):
  File "./princess", line 191, in <module>
    main()
  File "./princess", line 186, in main
    args = get_args()
  File "./princess", line 53, in get_args
    args.func(args, unknownargs)
  File "./princess", line 139, in run_princess
    subprocess.run(['snakemake',  '-p', '-j', number_of_jobs, '--cluster-config', cluster_config, '--config', sample_dir, sample_names, *unknownargs], check=True, universal_newlines=True)
  File "/root/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['snakemake', '-p', '-j', '200', '--cluster-config', '/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/cluster_config.yaml', '--config', 'sample_directory=/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37', 'sample_list=NA12878.pcr.MSssI.simpson.021016.R1_001.fastq.gz NA12878.pcr.MSssI.simpson.021016.R2_001.fastq.gz', 'read_type=ont', '--use-conda']' returned non-zero exit status 1.

best，
XFY

**Comment by NGLJ** [comment]
HI,
When run princess, need to build conda environment in the output directory.Such as:
    Building DAG of jobs...
    Creating conda environment envs/princess_env.yaml...
    Downloading and installing remote packages.
    Environment for envs/princess_env.yaml created (location: .snakemake/conda/42435982)
    Creating conda environment envs/clair_env.yaml...
    Downloading and installing remote packages.
    Environment for envs/clair_env.yaml created (location: .snakemake/conda/cbd00219)

How I can build conda environment in specific directory before runing  princess.

best,
XFY

**Comment by NGLJ** [comment]
HI,
config.yaml:
# Information about reference
###########################
ref: ['37']
references:
  '37': "/mnt/data1/lixinyue/data/hg19.fa"
  '38': ""
chr_list:
  '37': ['chr1','chr2','chr3','chr4'] #['1','2','3']
  '38': [""] #[chr1,chr2]
###########################

When test multiple chromosomes on a local machine,such as ['chr1','chr2','chr3','chr4'],an error occurred.


Traceback (most recent call last):
  File "/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/conda_env/6fcbc117/bin/clair/../clair.py", line 92, in <module>
    main()
  File "/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/conda_env/6fcbc117/bin/clair/../clair.py", line 86, in main
    submodule.main()
  File "/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/conda_env/6fcbc117/bin/dataPrepScripts/CreateTensor.py", line 440, in main
    OutputAlnTensor(args)
  File "/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/conda_env/6fcbc117/bin/dataPrepScripts/CreateTensor.py", line 372, in OutputAlnTensor
    tensor_fp.stdin.write(l)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
call_variant.py exited with exceptions. Exiting...
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
[Mon Feb 17 21:09:13 2020]
Error in rule call_snps_chunk:
    jobid: 55
    output: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/snp/minimap/data.split.chr3_2.vcf
    conda-env: /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/conda_env/6fcbc117
    shell:

        export PATH=$PWD/bin/pypy/bin:$PATH &&         clair.py callVarBam             --chkpnt_fn /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/bin/modules/ont/model             --bam_fn /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/align/minimap/data.bam             --ref_fn /mnt/data1/lixinyue/data/hg19.fa             --minCoverage 2             --ctgName chr3             --ctgStart 56577836             --ctgEnd 84866754             --threads 5 --call_fn /mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/snp/minimap/data.split.chr3_2.vcf

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job call_snps_chunk since they might be corrupted:
/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/snp/minimap/data.split.chr3_2.vcf
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1

best,
XFY

**Comment by MeHelmy** [comment]
Thank you for reaching back,

Is there an error file contain the word `bam_2_tab` It should be in the directory `/mnt/data1/lixinyue/docker/test_xfy/princess/princess-master/analysis_37/snake_log`.

Edit:
I am assuming that the Bam file did not have phased reads which caused the problem, please send me your e-mail I will send you full chr22 data set to test with.


~Best,
Medhat

**Comment by ainovice1992** [comment]
My email is xufengyao1@huawei.com.Thanks a lot for sharing data.
best,
XFY

**Comment by ainovice1992** [comment]
HI,
We test allchromosomea on computer with 16 core and 10 GB memory，the error is as follows：

45 of 209 steps (22%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
mkdir -p /output/snake_log &&    find . -maxdepth 1 -name 'snakejob.*' -type f -print0 | xargs -0r mv -t /output/snake_log &&    cat pictures/fail.txt

Is memory shortage?

best,
XFY

**Comment by MeHelmy** [comment]
Hi!
I can not confirm that this is an Memory issue, please support me with the error message.

~Best,
Medhat
