### ISSUE TITLE
align stage completed successfully but small align bam

### ISSUE THREAD

**Issue by rozaimirazali** [MeHelmy/princess#5]
Hello.

I ran the _align_ command

> bsub -q normal -e ../logs/align.e -o ../logs/align.o -n 32 "princess align -d ../output/17092020 --ReadType clr -u -e --Aligner minimap --samplesFiles list.txt --ref /gpfs/projects/ymokrab_Lab/REF/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/input/ref/GRCh37.fa --jobs 200 --log align.log"

and it ended succesfully 

> Building DAG of jobs...
> Using shell: /usr/bin/bash
> Provided cores: 200
> Rules claiming more threads will be scaled down.
> Job counts:
>         count   jobs
>         1       indexBam
>         1       mergeAlign
>         1       minimap2
>         3
> cat pictures/start.txt
> 
> [Thu Sep 17 16:45:25 2020]
> Job 1: Running minimap2 , sample is: list.txt
> 
> 
>             minimap2  -ax map-pb "/gpfs/projects/ymokrab_Lab/REF/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/input/ref/GRCh37.fa"  "/gpfs/projects/ymokrab_Lab/SDR400076/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/output/17092020/list.txt" -H "--MD" -t "5" | samtools sort -@ 5 - > "/gpfs/projects/ymokrab_Lab/SDR400076/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/output/17092020/align/minimap/list.txt.bam"
> 
> [Thu Sep 17 16:46:30 2020]
> Finished job 1.
> 1 of 3 steps (33%) done
> 
> [Thu Sep 17 16:46:30 2020]
> Job 2: Indexing /gpfs/projects/ymokrab_Lab/SDR400076/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/output/17092020/align/minimap/list.txt.bam
> 
> samtools index /gpfs/projects/ymokrab_Lab/SDR400076/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/output/17092020/align/minimap/list.txt.bam
> [Thu Sep 17 16:46:30 2020]
> Finished job 2.
> 2 of 3 steps (67%) done
> 
> [Thu Sep 17 16:46:30 2020]
> Job 0: Mergeing data
> 
> 
>         samtools merge -@ 5 /gpfs/projects/ymokrab_Lab/SDR400076/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/output/17092020/align/minimap/data.bam /gpfs/projects/ymokrab_Lab/SDR400076/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/output/17092020/align/minimap/list.txt.bam > /gpfs/projects/ymokrab_Lab/SDR400076/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/output/17092020/align/minimap/merge.log 2>&1
> 
> [Thu Sep 17 16:46:30 2020]
> Finished job 0.
> 3 of 3 steps (100%) done
> Complete log: /gpfs/projects/ymokrab_Lab/SDR400076/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/output/17092020/.snakemake/log/2020-09-17T164524.510866.snakemake.log
> mkdir -p /gpfs/projects/ymokrab_Lab/SDR400076/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/output/17092020/snake_log &&    find . -maxdepth 1 -name 'snakejob.*' -type f -print0 | xargs -0r mv -t /gpfs/projects/ymokrab_Lab/SDR400076/REF005_Long_read_structural_variants/princess/MNDY02/MNDY0201/output/17092020/snake_log &&    cat pictures/success.txt

but the output bam seems very small. I tried to check the stderr and the log files but did not find anything wrong. Could you please advise ?

> -rw-rw---- 1 rmohamadrazali sysbio 1.5K Sep 17 16:46 list.txt.bam
> -rw-rw---- 1 rmohamadrazali sysbio    0 Sep 17 16:46 list.txt.log
> -rw-rw---- 1 rmohamadrazali sysbio  688 Sep 17 16:46 list.txt.bam.bai
> -rw-rw---- 1 rmohamadrazali sysbio    0 Sep 17 16:46 merge.log
> -rw-rw---- 1 rmohamadrazali sysbio 1.5K Sep 17 16:46 data.bam

**Comment by MeHelmy** [comment]
Thank you for reaching back,

The -s command in Princess accepts a list of fasta/fastq files (it could be gzipped also), but you supported it with a text file.

Thanks
